# Generated by Django 4.0.5 on 2022-10-26 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('revision', models.IntegerField(default=0)),
                ('product_category', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
